#!/usr/bin/env python3
"""Require one exact Poetry version across source, lock, CI, and container."""

from __future__ import annotations

import argparse
import re
import subprocess
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VERSION = re.compile(r"^[0-9]+\.[0-9]+\.[0-9]+$")
LOCK_HEADER = re.compile(
    r"^# This file is automatically @generated by Poetry ([^ ]+) "
    r"and should not be changed by hand\.$"
)


def required_version() -> str:
    project = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    value = project["tool"]["poetry"].get("requires-poetry")
    if not isinstance(value, str) or VERSION.fullmatch(value) is None:
        raise ValueError("[tool.poetry].requires-poetry must be one exact X.Y.Z")
    return value


def repository_errors() -> tuple[str, ...]:
    wanted = required_version()
    errors: list[str] = []
    first_line = (ROOT / "poetry.lock").read_text(encoding="utf-8").splitlines()[0]
    match = LOCK_HEADER.fullmatch(first_line)
    actual = match.group(1) if match else "unrecognised"
    if actual != wanted:
        errors.append(f"poetry.lock generator is {actual}; expected {wanted}")

    workflow = (ROOT / ".github/workflows/ci.yml").read_text(encoding="utf-8")
    if f'POETRY_VERSION: "{wanted}"' not in workflow:
        errors.append("CI Poetry version does not match pyproject.toml")

    dockerfile = (ROOT / "Dockerfile").read_text(encoding="utf-8")
    if f"ARG POETRY_VERSION={wanted}" not in dockerfile:
        errors.append("Docker Poetry version does not match pyproject.toml")
    return tuple(errors)


def active_error() -> str | None:
    wanted = required_version()
    result = subprocess.run(
        ["poetry", "--version"],
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        return f"cannot execute required Poetry {wanted}"
    if result.stdout.strip() != f"Poetry (version {wanted})":
        return f"active Poetry is not the required {wanted}"
    return None


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--active", action="store_true")
    args = parser.parse_args()
    errors = list(repository_errors())
    if args.active and (error := active_error()) is not None:
        errors.append(error)
    if errors:
        for error in errors:
            print(f"error: {error}")
        return 1
    print(f"Poetry toolchain contract holds at {required_version()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
